# Generated by Django 3.0.5 on 2020-04-20 12:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_category', models.CharField(max_length=200)),
                ('blog_summary', models.CharField(max_length=200)),
                ('category_slug', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='BlogSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_series', models.CharField(max_length=200)),
                ('blog_summary', models.CharField(max_length=200)),
                ('blog_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='blog_index.BlogCategory', verbose_name='Category')),
            ],
            options={
                'verbose_name_plural': 'Series',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=200)),
                ('blog_content', models.TextField()),
                ('blog_published', models.DateTimeField(default=datetime.datetime(2020, 4, 20, 12, 1, 8, 452386), verbose_name='DatePublished')),
                ('blog_author', models.CharField(max_length=200)),
                ('blog_slug', models.CharField(default=1, max_length=200)),
                ('blog_series', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='blog_index.BlogSeries', verbose_name='Series')),
            ],
        ),
    ]
