# Generated by Django 3.0.5 on 2020-04-20 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 20, 15, 46, 58, 306657), verbose_name='DatePublished'),
        ),
    ]
